### PR TITLE
add docs

### PR DESCRIPTION
**Pull request by yun-long**
add docs

### CODE REVIEW

**Review by foehnx — CHANGES_REQUESTED** [review]
few comments:

* is there a reason that there is a `.vscode` folder in here?
* is the `_build` folder necessary?

**Review by foehnx — APPROVED** [review]
LGTM

**Review by foehnx — APPROVED** [review]
LGTM, please merge.
I will follow up with one including the doxygen.
You don't have to wait with the merge.

**Comment by roangel** [comment]
Agree

**Pull request merged**
